require'nvim-treesitter.configs'.setup {
  ensure_installed = {
      "bash",
      "bibtex",
      "c",
      "cmake",
      "cpp",
      "css",
      "dart",
      "dockerfile",
      "go",
      "html",
      "java",
      "javascript",
      "jsdoc",
      "json",
      "json5",
      "jsonc",
      "kotlin",
      "latex",
      "make",
      "python",
      "r",
      "regex",
      "ruby",
      "rust",
      "scala",
      "scss",
      "svelte",
      "toml",
      "tsx",
      "typescript",
      "yaml",
  },
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = false,
  },
}
